services:
  Mink67\Security\Security\KeycloakAuthenticator:
    class: Mink67\Security\Security\KeycloakAuthenticator
    autowire: true

  Mink67\Security\User\OAuthUserProvider:
    class: Mink67\Security\User\OAuthUserProvider
    autowire: true

  Mink67\Security\Converters\AccessTokenToUser:
    class: Mink67\Security\Converters\AccessTokenToUser
    arguments:
      $jwk_url: '%mink67.security.jwk_url%'
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $baseConverter: '@Mink67\OpenidConnect\AccessTokenToUser'
  Mink67\OpenidConnect\Contracts\User\OAuthUserProvider:
    class: Mink67\Security\User\OpenidConnect\OAuthUserProvider
    autowire: true
  Mink67\OpenidConnect\AccessTokenToUser:
    class: Mink67\OpenidConnect\AccessTokenToUser
    autowire: true

  Mink67\Security\Services\TokenManager:
    class: Mink67\Security\Services\TokenManager
    autowire: true

  Mink67\Security\Services\User\Get:
    class: Mink67\Security\Services\User\Get
    autowire: true

  
  Mink67\Security\Services\User\GetAll:
    class: Mink67\Security\Services\User\GetAll
    autowire: true

  
  Mink67\Security\Services\User\ByRole:
    class: Mink67\Security\Services\User\ByRole
    autowire: true

  
  Mink67\Security\Services\User\ByGroup:
    class: Mink67\Security\Services\User\ByGroup
    autowire: true